{% set version = "0.1.16" %}

package:
  name: iso8601
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iso8601/iso8601-{{ version }}.tar.gz
  sha256: 36532f77cc800594e8f16641edae7f1baf7932f05d8e508545b95fc53c6dc85b

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - poetry-core >=1.0.0
  run:
    - python

test:
  imports:
    - iso8601
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple module to parse ISO 8601 dates'
  doc_url: http://pyiso8601.readthedocs.io/en/latest/
  dev_url: https://github.com/micktwomey/pyiso8601

extra:
    recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
