{% set version = "1.0.0" %}

package:
  name: iso8601
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iso8601/iso8601-{{ version }}.tar.gz
  sha256: 79ec9749f8bf35ffae77f835e80e96d2f95affa0f79d3d7b25c0fa7e06207a8b

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - poetry-core >=1.0.0
  run:
    - python

test:
  imports:
    - iso8601
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple module to parse ISO 8601 dates'
  doc_url: http://pyiso8601.readthedocs.io/en/latest/
  dev_url: https://github.com/micktwomey/pyiso8601

extra:
    recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
