{% set version = "0.1.14" %}

package:
  name: iso8601
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iso8601/iso8601-{{ version }}.tar.gz
  sha256: 8aafd56fa0290496c5edbb13c311f78fa3a241f0853540da09d9363eae3ebd79

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - iso8601

about:
  home: https://bitbucket.org/micktwomey/pyiso8601
  license: MIT
  summary: 'Simple module to parse ISO 8601 dates'
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
    recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
