travis:
  secure:
    BINSTAR_TOKEN: Yn/8jcPRuqTE2Z8GwPAjiYih8O4mC/vW72ozTu85c/XuZBddBN8qqn/Z+fjNa1r6CxMPGba4MMtzh7G8iJXv1U04MF/rdRDwaiu0OybL2Lh+BvdzG95agF1rmD66FjNA1GypIQ/446DqoPZzxmG1gZOztkp/1usD6AIgKiKSbf3vRPmG0EKHEjkF3yImBwmAWDt++fTATeXLWwuJYi7rQc/WThFAZBCdN74iIXvu3JzuUS9/yRKwFbd1vsImHjYJrTXzMXLUz4qHHHRKM7vHPREjoiPEw/ql4ehNQ6SeTFij2umcJQ2jsnxScXukYl0T0UJzOlhrWGPrXVrJRpTUvqgHb0QliREva03Dm2Z4kVA5TpkSgbUnWhUy2vHL550uArh7NaCV/2vg7y7HB4iwPWjXDIl3wOmFoyxLGu226c0ZHGIiv691m0eAl//Q3/pszsbvk9fYvTHcBLeHB6qyRD+UpkwLYXxV1mO8afktKHKoy8bKWhsrvBavuRFodPfMjza3UrL9jLK7kils4xuYzDR7Ey65g8Jn4mnFpGiAikz1iZOLQRW7CAS+nidRJlCZdrR5EC4bMBYLf47RuX5a0//q96UjHs1xyW4mp70u/rDOYYIzHJil88ixmi3aa23MC3yk7mh64+eq8hmaWV4Bb5ll22bNj3na994gcQJ8Gfw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
